<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>8da1ddf5-e5ad-42c8-a212-130fd1a2653e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EShop.ApiService\EShop.ApiService.csproj" />
    <ProjectReference Include="..\EShop.Web\EShop.Web.csproj" />
  </ItemGroup>

</Project>
